### ISSUE TITLE
[Anwenden kann nicht ausgewählt werden]

### ISSUE THREAD

**Issue by KatrinBrabender** [AID-Labor/classifier#7]
**Beschreibung des Bugs**
Legt man Methoden /  Attribute an, ist der Button Anwenden nicht anklickbar.

**Reproduzierbarkeit**
Schritte, um das Problem zu reproduzieren (falls möglich):
1. Gehe zu '...'
2. Klicke auf '....'
3. Scrolle zu '....'
4. Fehler ist hier zu sehen

**Erwartetes Verhalten**
Beschreibung, wie sich das Programm ohne Fehler verhalten sollte.

**Screenshots**
Falls möglich, ist es hilfreich Screenshots des Fehlers hinzuzufügen.

**Systeminformationen:**
 - OS: [z.B. Windows 10]
 - Version des Programms [z.B. 1.0.0-SNAPSHOT-1]

**Zusätzliche Informationen**
Hier ist Platz für zusätzliche Informationen.

**Logging**
Falls möglich kann eine Log-Datei hinzugefügt werden. Diese wird systemabhängig im Programmordner gespeichert:
- Windows: `%LOCALAPPDATA%\Classifier\log`
- macOS: `~/Library/Classifier/log`
- Linux: `~/.config/Classifier/log`

**Comment by encrypTimM** [comment]
Der 'Anwenden'-Button sollte funktionieren, es gibt allerdings eine kleine Validierung, die erfüllt sein muss. Wenn Attribute oder Methoden hinzugefügt werden, muss ein Name angegeben werden, zudem muss der Datentyp/Rückgabetyp und bei allen Parametern ebenfalls Name und Datentyp angegeben werden.

Löst die Beschreibung das Problem?
